// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp2N_vVVuYmSqvbxefw6brhUqQq5O73OE',
    appId: '1:915666511366:web:3138a1c98600af517b4587',
    messagingSenderId: '915666511366',
    projectId: 'online-learning-app-35970',
    authDomain: 'online-learning-app-35970.firebaseapp.com',
    storageBucket: 'online-learning-app-35970.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3LDt3a_FpbGlQ_Nganz4noiCRSapjDPs',
    appId: '1:915666511366:android:f294e7e613b6ac477b4587',
    messagingSenderId: '915666511366',
    projectId: 'online-learning-app-35970',
    storageBucket: 'online-learning-app-35970.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABtJbsqcMD4vVcwocXekaEFuzOWmRd7qk',
    appId: '1:915666511366:ios:b5c76a27a4594a637b4587',
    messagingSenderId: '915666511366',
    projectId: 'online-learning-app-35970',
    storageBucket: 'online-learning-app-35970.appspot.com',
    iosBundleId: 'com.example.onlineLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABtJbsqcMD4vVcwocXekaEFuzOWmRd7qk',
    appId: '1:915666511366:ios:9119b22d9a1a79107b4587',
    messagingSenderId: '915666511366',
    projectId: 'online-learning-app-35970',
    storageBucket: 'online-learning-app-35970.appspot.com',
    iosBundleId: 'com.example.onlineLearning.RunnerTests',
  );
}
